### PR TITLE
Add Python 3 to test matrix

### PR DESCRIPTION
**Pull request by abitrolly**
This removes Python matrix from actions workflow, because tested Python versions are configured in `tox.ini`.

### CODE REVIEW

**Comment by fschulze** [comment]
I like to keep the matrix as it is easier to see which version fails. You might want to add the explicit environment instead, see:
https://github.com/devpi/devpi/blob/main/.github/workflows/main.yml#L61
https://github.com/devpi/devpi/blob/main/.github/workflows/main.yml#L85

**Comment by abitrolly** [comment]
I added Python 3.10 to the `tox` matrix and now tests fail. I am adding GitHub Action environment for selecting Python for `tox`.

**Comment by abitrolly** [comment]
Added `tox` + GitHub Actions matrix. Now need to fix the tests.

**Comment by nhoening** [comment]
#14 might have some useful things to work from. I only had one problem with that work, see comments.

**Pull request merged**
