### PR TITLE
fix metadata.bind removal bug in sql alchemy 2.0

### PR DESCRIPTION
**Pull request by ankona**
The metadata.bind property has been removed in SQLAlchemy 2.0. This fix allows passing an engine to enable performing index retrieval in sqla 2

### CODE REVIEW

**Review by bkt92 — APPROVED** [review]
The fix is valid, tested, and worked with SQLachemy 2.0

**Comment by schettino72** [comment]
This worked for me as well.
Just note that apart from the `metadata` parameter I had also to pass the `engine` parameter.

**Review by Zlopez — APPROVED** [review]
This looks like it should fix some of the errors I see in the tests.

**Comment by Zlopez** [comment]
Closing this as it's already implemented in https://github.com/fschulze/sqlalchemy_schemadisplay/pull/35 which I merged

**Pull request closed without merging**
